name: py36
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - numpy=1.16.4
  - pandas=0.25.1
  - python=3.6.9
  - scikit-learn=0.21.1
  - scipy=1.4.1
  - seaborn=0.10.1
  - six=1.12.0
  - sqlalchemy=1.3.7
  - sqlite=3.29.0
